version: '3.8'

services:
  postgres:
    image: postgres:latest
    # container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
  redis: 
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --------------------------------------------ส่วนของ back-end-api --------------------------------------------------------------------------------------------    
  
  backend_api:
    # image: backend_api
    container_name: backend_api
    build: .
    ports:
      - "7000:7000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
      - DB_DBNAME=mydatabase
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped  


    #   backend_api:
    # # image: backend_api
    # container_name: backend_api
    # ports:
    #   - "7000:7000"
    # environment:
    #   - DB_HOST=postgres
    #   - DB_PORT=5432
    #   - DB_USER=myuser
    #   - DB_PASSWORD=mypassword
    #   - DB_NAME=mydatabase
    # env_file:
    #   - .env
    # #   -./config.yaml
    # build:
    #   context:.
    # depends_on:
    #   - postgres
    # # volumes:
    # #   - ./config.yaml:/app/config.yaml
    # restart: unless-stopped 

volumes:
  postgres_data:
  redis_data:

